name: 构建 OpenWrt 固件

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenWrt 版本号 (24.10.0)'
        required: true
        default: '24.10.0'
      target:
        description: '目标架构 (x86)'
        required: true
        default: 'x86'
      subtarget:
        description: '子目标 (64)'
        required: true
        default: '64'
      profile:
        description: '设备配置文件 (generic)'
        required: true
        default: 'generic'
      rootfs_size:
        description: '根文件系统分区大小 (MiB, 1024)'
        required: true
        default: '1024'

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4

      - name: 安装依赖工具
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd build-essential libncurses5-dev gawk git gettext make gcc g++ unzip file python3 python3-venv python3-pip
          echo "检查已安装的包"
          dpkg -l | grep -E 'zstd|build-essential|libncurses5-dev|gawk|git|gettext|make|gcc|g\+\+|unzip|file|python3'
          echo "检查 make 和 python3 版本"
          make --version
          python3 --version

      - name: 清理工作目录
        run: |
          echo "清理当前工作目录以避免缓存问题"
          rm -rf *.tar.zst *.tar openwrt-imagebuilder-* sha256sums
          ls -l

      - name: 下载并验证 OpenWrt 镜像构建工具
        run: |
          URL="https://downloads.openwrt.org/releases/${{ inputs.version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/openwrt-imagebuilder-${{ inputs.version }}-${{ inputs.target }}-${{ inputs.subtarget }}.Linux-x86_64.tar.zst"
          SHA256SUMS_URL="https://downloads.openwrt.org/releases/${{ inputs.version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/sha256sums"
          echo "正在下载 Image Builder: $URL"
          wget --no-cache "$URL" || { echo "主服务器下载失败，尝试镜像服务器"; wget --no-cache "http://mirror2.openwrt.org/releases/${{ inputs.version }}/targets/${{ inputs.target }}/${{ inputs.subtarget }}/openwrt-imagebuilder-${{ inputs.version }}-${{ inputs.target }}-${{ inputs.subtarget }}.Linux-x86_64.tar.zst" || { echo "镜像服务器也失败，请检查 URL 或网络"; exit 1; }; }
          echo "下载校验和文件"
          wget --no-cache "$SHA256SUMS_URL" || { echo "下载校验和文件失败"; exit 1; }
          echo "验证 Image Builder 文件完整性"
          sha256sum -c sha256sums --ignore-missing | grep "openwrt-imagebuilder-${{ inputs.version }}-${{ inputs.target }}-${{ inputs.subtarget }}.Linux-x86_64.tar.zst" || { echo "校验和验证失败，文件可能损坏"; exit 1; }
          echo "解压 zst 文件"
          zstd -d *.tar.zst || { echo "zstd 解压失败"; exit 1; }
          echo "解压 tar 文件"
          tar -xvf *.tar || { echo "tar 解压失败"; exit 1; }
          echo "列出当前目录内容"
          ls -l
          echo "进入 Image Builder 目录"
          IMAGE_BUILDER_DIR="openwrt-imagebuilder-${{ inputs.version }}-${{ inputs.target }}-${{ inputs.subtarget }}.Linux-x86_64"
          echo "目标目录: $IMAGE_BUILDER_DIR"
          cd "$IMAGE_BUILDER_DIR" || { echo "进入 Image Builder 目录失败，目录名可能不正确"; ls -l; exit 1; }
          echo "检查 Makefile 是否存在"
          if [ ! -f Makefile ]; then
            echo "Makefile 不存在，ImageBuilder 目录可能损坏"
            ls -l
            exit 1
          fi
          echo "检查 defconfig 目标是否在 Makefile 中"
          if ! grep -q "defconfig:" Makefile; then
            echo "Makefile 中缺少 defconfig 目标，ImageBuilder 可能不完整"
            cat Makefile
            exit 1
          fi
          echo "检查关键目录和文件"
          ls -lR scripts/config 2>/dev/null || echo "scripts/config 目录缺失"
          ls -lR package/ 2>/dev/null | head -n 20 || echo "package 目录缺失"
          echo "当前目录: $(pwd)"
          ls -lR | head -n 100

      - name: 更新软件源
        working-directory: ./openwrt-imagebuilder-${{ inputs.version }}-${{ inputs.target }}-${{ inputs.subtarget }}.Linux-x86_64
        run: |
          echo "软件源配置内容（原始）:"
          cat repositories.conf
          echo "检查 Makefile 是否存在"
          if [ ! -f Makefile ]; then
            echo "Makefile 不存在，ImageBuilder 目录可能损坏"
            ls -l
            exit 1
          fi
          echo "检查 defconfig 目标是否在 Makefile 中"
          if ! grep -q "defconfig:" Makefile; then
            echo "Makefile 中缺少 defconfig 目标，ImageBuilder 可能不完整"
            cat Makefile
            exit 1
          fi
          echo "执行 make defconfig"
          make defconfig V=99 || { echo "make defconfig 失败"; ls -lR | head -n 100; cat repositories.conf; exit 1; }

      - name: 构建自定义固件
        working-directory: ./openwrt-imagebuilder-${{ inputs.version }}-${{ inputs.target }}-${{ inputs.subtarget }}.Linux-x86_64
        run: |
          PACKAGES="luci luci-theme-argon dnsmasq-full -dnsmasq"
          echo "开始构建固件，包列表: $PACKAGES"
          make image PROFILE="${{ inputs.profile }}" PACKAGES="$PACKAGES" EXTRA_IMAGE_NAME="自定义" ROOTFS_PARTSIZE="${{ inputs.rootfs_size }}" || { echo "构建固件失败"; exit 1; }

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-固件
          path: ./openwrt-imagebuilder-${{ inputs.version }}-${{ inputs.target }}-${{ inputs.subtarget }}.Linux-x86_64/bin/targets/${{ inputs.target }}/${{ inputs.subtarget }}/*
